#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

const int FRAMES_PER_SEC = 10;

enum Direction{
	DIRECTION_NONE, DIRECTION_UP, DIRECTION_DOWN, DIRECTION_LEFT, DIRECTION_RIGHT, DIRECTION_COUNT
};

#endif